// packages/sdk-angular/src/index.ts
/**
 * Rollgate Angular SDK
 *
 * Thin wrapper around @rollgate/sdk-browser providing Angular-specific bindings:
 * - RollgateService (Injectable service)
 * - RollgateModule (NgModule)
 * - FeatureDirective (*rollgateFeature structural directive)
 *
 * All HTTP, caching, circuit breaker logic is delegated to sdk-browser.
 */
import {
  Injectable,
  NgModule,
  ModuleWithProviders,
  InjectionToken,
  Inject,
  Directive,
  Input,
  TemplateRef,
  ViewContainerRef,
  OnInit,
  OnDestroy,
} from "@angular/core";
import { BehaviorSubject, Observable, Subscription } from "rxjs";
import {
  createClient,
  RollgateBrowserClient,
  CircuitState,
} from "@rollgate/sdk-browser";
import type {
  UserContext,
  RollgateOptions,
  MetricsSnapshot,
  EvaluationReason,
  EvaluationDetail,
  TrackEventOptions,
} from "@rollgate/sdk-browser";

// Re-export types from sdk-browser
export type {
  UserContext,
  RollgateOptions,
  MetricsSnapshot,
  EvaluationReason,
  EvaluationDetail,
  TrackEventOptions,
} from "@rollgate/sdk-browser";
export {
  CircuitState,
  CircuitOpenError,
  RollgateError,
  ErrorCategory,
} from "@rollgate/sdk-browser";

/**
 * Angular SDK configuration
 */
export interface RollgateConfig extends RollgateOptions {
  /** Your Rollgate API key */
  apiKey: string;
  /** Initial user context */
  user?: UserContext;
}

/** Injection token for Rollgate config */
export const ROLLGATE_CONFIG = new InjectionToken<RollgateConfig>(
  "ROLLGATE_CONFIG",
);

/**
 * Rollgate Angular Service
 *
 * Injectable service for feature flag management.
 *
 * @example
 * ```typescript
 * @Component({ ... })
 * export class MyComponent {
 *   constructor(private rollgate: RollgateService) {}
 *
 *   get showFeature() {
 *     return this.rollgate.isEnabled('new-feature');
 *   }
 * }
 * ```
 */
@Injectable({ providedIn: "root" })
export class RollgateService implements OnDestroy {
  private client: RollgateBrowserClient | null = null;

  private readonly _flags$ = new BehaviorSubject<Record<string, boolean>>({});
  private readonly _isLoading$ = new BehaviorSubject<boolean>(true);
  private readonly _isError$ = new BehaviorSubject<boolean>(false);
  private readonly _isStale$ = new BehaviorSubject<boolean>(false);
  private readonly _circuitState$ = new BehaviorSubject<CircuitState>(
    CircuitState.CLOSED,
  );
  private readonly _isReady$ = new BehaviorSubject<boolean>(false);

  /** Observable of all flags */
  readonly flags$: Observable<Record<string, boolean>> =
    this._flags$.asObservable();
  /** Observable of loading state */
  readonly isLoading$: Observable<boolean> = this._isLoading$.asObservable();
  /** Observable of error state */
  readonly isError$: Observable<boolean> = this._isError$.asObservable();
  /** Observable of stale state */
  readonly isStale$: Observable<boolean> = this._isStale$.asObservable();
  /** Observable of circuit breaker state */
  readonly circuitState$: Observable<CircuitState> =
    this._circuitState$.asObservable();
  /** Observable of ready state */
  readonly isReady$: Observable<boolean> = this._isReady$.asObservable();

  constructor(@Inject(ROLLGATE_CONFIG) private config: RollgateConfig) {
    this.initialize();
  }

  private initialize(): void {
    const { apiKey, user, ...options } = this.config;
    this.client = createClient(apiKey, user || null, options);

    // Subscribe to client events
    this.client.on("ready", () => {
      this._flags$.next(this.client!.allFlags());
      this._isLoading$.next(false);
      this._isError$.next(false);
      this._isStale$.next(false);
      this._isReady$.next(true);
    });

    this.client.on("flags-updated", (newFlags) => {
      this._flags$.next(newFlags as Record<string, boolean>);
      this._isStale$.next(false);
    });

    this.client.on("error", () => {
      this._isError$.next(true);
      const currentFlags = this.client!.allFlags();
      if (Object.keys(currentFlags).length > 0) {
        this._flags$.next(currentFlags);
        this._isStale$.next(true);
      }
    });

    this.client.on("circuit-state-change", (data) => {
      const stateData = data as { to: CircuitState };
      this._circuitState$.next(stateData.to);
    });

    // Wait for initialization
    this.client.waitForInitialization().catch(() => {
      this._isError$.next(true);
      this._isLoading$.next(false);
    });
  }

  /**
   * Check if a flag is enabled
   */
  isEnabled(flagKey: string, defaultValue: boolean = false): boolean {
    if (this.client) {
      return this.client.isEnabled(flagKey, defaultValue);
    }
    return defaultValue;
  }

  /**
   * Check if a flag is enabled with evaluation reason
   */
  isEnabledDetail(
    flagKey: string,
    defaultValue: boolean = false,
  ): EvaluationDetail<boolean> {
    if (this.client) {
      return this.client.isEnabledDetail(flagKey, defaultValue);
    }
    return {
      value: defaultValue,
      reason: { kind: "ERROR", errorKind: "CLIENT_NOT_READY" },
    };
  }

  /**
   * Get current flags snapshot
   */
  get flags(): Record<string, boolean> {
    return this._flags$.getValue();
  }

  /**
   * Get current loading state
   */
  get isLoading(): boolean {
    return this._isLoading$.getValue();
  }

  /**
   * Get current error state
   */
  get isError(): boolean {
    return this._isError$.getValue();
  }

  /**
   * Get current stale state
   */
  get isStale(): boolean {
    return this._isStale$.getValue();
  }

  /**
   * Get current circuit breaker state
   */
  get circuitState(): CircuitState {
    return this._circuitState$.getValue();
  }

  /**
   * Check if client is ready
   */
  get isReady(): boolean {
    return this._isReady$.getValue();
  }

  /**
   * Change user context
   */
  async identify(user: UserContext): Promise<void> {
    if (this.client) {
      await this.client.identify(user);
    }
  }

  /**
   * Clear user context
   */
  async reset(): Promise<void> {
    if (this.client) {
      await this.client.reset();
    }
  }

  /**
   * Force refresh flags
   */
  async refresh(): Promise<void> {
    if (this.client) {
      await this.client.refresh();
    }
  }

  /**
   * Get metrics snapshot
   */
  getMetrics(): MetricsSnapshot {
    if (this.client) {
      return this.client.getMetrics();
    }
    return {
      totalRequests: 0,
      successfulRequests: 0,
      failedRequests: 0,
      successRate: 0,
      errorRate: 0,
      avgLatencyMs: 0,
      minLatencyMs: 0,
      maxLatencyMs: 0,
      p50LatencyMs: 0,
      p95LatencyMs: 0,
      p99LatencyMs: 0,
      cacheHits: 0,
      cacheMisses: 0,
      cacheHitRate: 0,
      notModifiedResponses: 0,
      errorsByCategory: {},
      circuitOpens: 0,
      circuitCloses: 0,
      circuitState: "closed",
      flagEvaluations: {
        totalEvaluations: 0,
        evaluationsPerFlag: {},
        avgEvaluationTimeMs: 0,
      },
      windows: {
        "1m": { requests: 0, errors: 0, avgLatencyMs: 0, errorRate: 0 },
        "5m": { requests: 0, errors: 0, avgLatencyMs: 0, errorRate: 0 },
        "15m": { requests: 0, errors: 0, avgLatencyMs: 0, errorRate: 0 },
        "1h": { requests: 0, errors: 0, avgLatencyMs: 0, errorRate: 0 },
      },
      uptimeMs: 0,
      lastRequestAt: null,
    };
  }

  /**
   * Track a conversion event for A/B testing
   */
  track(options: TrackEventOptions): void {
    if (this.client) {
      this.client.track(options);
    }
  }

  ngOnDestroy(): void {
    if (this.client) {
      this.client.close();
      this.client = null;
    }
  }
}

/**
 * Structural directive for conditional rendering based on feature flags
 *
 * @example
 * ```html
 * <div *rollgateFeature="'new-feature'">
 *   New feature content
 * </div>
 *
 * <ng-template [rollgateFeature]="'premium-feature'" [rollgateFeatureElse]="freeTpl">
 *   Premium content
 * </ng-template>
 * <ng-template #freeTpl>Free content</ng-template>
 * ```
 */
@Directive({
  selector: "[rollgateFeature]",
})
export class FeatureDirective implements OnInit, OnDestroy {
  @Input() rollgateFeature!: string;
  @Input() rollgateFeatureElse?: TemplateRef<unknown>;

  private subscription?: Subscription;

  constructor(
    private templateRef: TemplateRef<unknown>,
    private viewContainer: ViewContainerRef,
    private rollgate: RollgateService,
  ) {}

  ngOnInit(): void {
    this.subscription = this.rollgate.flags$.subscribe(() => {
      this.updateView();
    });
    this.updateView();
  }

  private updateView(): void {
    this.viewContainer.clear();
    if (this.rollgate.isEnabled(this.rollgateFeature)) {
      this.viewContainer.createEmbeddedView(this.templateRef);
    } else if (this.rollgateFeatureElse) {
      this.viewContainer.createEmbeddedView(this.rollgateFeatureElse);
    }
  }

  ngOnDestroy(): void {
    if (this.subscription) {
      this.subscription.unsubscribe();
    }
  }
}

/**
 * Rollgate Angular Module
 *
 * @example
 * ```typescript
 * @NgModule({
 *   imports: [
 *     RollgateModule.forRoot({
 *       apiKey: 'your-api-key',
 *       user: { id: 'user-1' }
 *     })
 *   ]
 * })
 * export class AppModule {}
 * ```
 */
@NgModule({
  declarations: [FeatureDirective],
  exports: [FeatureDirective],
})
export class RollgateModule {
  static forRoot(config: RollgateConfig): ModuleWithProviders<RollgateModule> {
    return {
      ngModule: RollgateModule,
      providers: [
        { provide: ROLLGATE_CONFIG, useValue: config },
        RollgateService,
      ],
    };
  }
}

// packages/sdk-react-native/src/index.ts
/**
 * Rollgate React Native SDK
 *
 * Feature flags for React Native apps with React hooks support.
 *
 * Usage:
 *   import { RollgateProvider, useFlag } from '@rollgate/sdk-react-native';
 *
 *   <RollgateProvider config={{ apiKey: 'your-key' }} user={{ id: 'user-1' }}>
 *     <App />
 *   </RollgateProvider>
 *
 *   const showFeature = useFlag('new-feature', false);
 */
import React, {
  createContext,
  useContext,
  useEffect,
  useState,
  useCallback,
  useRef,
  ReactNode,
} from "react";
import {
  createClient,
  RollgateReactNativeClient,
  CircuitState,
  RollgateError,
  ErrorCategory,
} from "./client";
import type {
  UserContext,
  RollgateOptions,
  MetricsSnapshot,
  RetryConfig,
  CircuitBreakerConfig,
  CacheConfig,
  EvaluationReason,
  EvaluationDetail,
  TrackEventOptions,
} from "./client";

// Re-export types and classes
export type {
  UserContext,
  RollgateOptions,
  MetricsSnapshot,
  RetryConfig,
  CircuitBreakerConfig,
  CacheConfig,
  EvaluationReason,
  EvaluationDetail,
  TrackEventOptions,
};
export {
  createClient,
  RollgateReactNativeClient,
  CircuitState,
  RollgateError,
  ErrorCategory,
};

/**
 * React Native SDK configuration
 */
export interface RollgateConfig extends RollgateOptions {
  /** Your Rollgate API key */
  apiKey: string;
}

interface RollgateContextValue {
  /** Check if a flag is enabled */
  isEnabled: (flagKey: string, defaultValue?: boolean) => boolean;
  /** True while initial flags are loading */
  isLoading: boolean;
  /** True if there was an error fetching flags */
  isError: boolean;
  /** True if using cached/stale flags */
  isStale: boolean;
  /** Current circuit breaker state */
  circuitState: CircuitState;
  /** All flags as key-value object */
  flags: Record<string, boolean>;
  /** Change user context */
  identify: (user: UserContext) => Promise<void>;
  /** Clear user context */
  reset: () => Promise<void>;
  /** Force refresh flags */
  refresh: () => Promise<void>;
  /** Get metrics snapshot */
  getMetrics: () => MetricsSnapshot;
  /** Track a conversion event for A/B testing */
  track: (options: TrackEventOptions) => void;
  /** Access the underlying client */
  client: RollgateReactNativeClient | null;
}

const RollgateContext = createContext<RollgateContextValue | null>(null);

interface RollgateProviderProps {
  config: RollgateConfig;
  user?: UserContext;
  children: ReactNode;
}

/**
 * Rollgate Provider component for React Native
 *
 * @example
 * ```tsx
 * <RollgateProvider config={{ apiKey: 'your-api-key' }} user={{ id: 'user-1' }}>
 *   <App />
 * </RollgateProvider>
 * ```
 */
export function RollgateProvider({
  config,
  user,
  children,
}: RollgateProviderProps) {
  const [flags, setFlags] = useState<Record<string, boolean>>({});
  const [isLoading, setIsLoading] = useState(true);
  const [isError, setIsError] = useState(false);
  const [isStale, setIsStale] = useState(false);
  const [circuitState, setCircuitState] = useState<CircuitState>(
    CircuitState.CLOSED,
  );

  const clientRef = useRef<RollgateReactNativeClient | null>(null);

  // Create client on mount
  useEffect(() => {
    const { apiKey, ...options } = config;

    const client = createClient(apiKey, user || null, options);
    clientRef.current = client;

    // Subscribe to client events
    client.on("ready", () => {
      setFlags(client.allFlags());
      setIsLoading(false);
      setIsError(false);
      setIsStale(false);
    });

    client.on("flags-updated", (newFlags) => {
      setFlags(newFlags as Record<string, boolean>);
      setIsStale(false);
    });

    client.on("error", () => {
      setIsError(true);
      // Use cached flags if available
      const currentFlags = client.allFlags();
      if (Object.keys(currentFlags).length > 0) {
        setFlags(currentFlags);
        setIsStale(true);
      }
    });

    client.on("circuit-state-change", (data) => {
      const stateData = data as { to: CircuitState };
      setCircuitState(stateData.to);
    });

    // Wait for initialization
    client.waitForInitialization().catch(() => {
      setIsError(true);
      setIsLoading(false);
    });

    return () => {
      client.close();
      clientRef.current = null;
    };
  }, [config.apiKey]); // Only recreate client if API key changes

  // Handle user changes
  useEffect(() => {
    if (clientRef.current && user) {
      clientRef.current.identify(user).catch(() => {
        setIsError(true);
      });
    }
  }, [user?.id, user?.email]);

  const isEnabled = useCallback(
    (flagKey: string, defaultValue: boolean = false): boolean => {
      if (clientRef.current) {
        return clientRef.current.isEnabled(flagKey, defaultValue);
      }
      return defaultValue;
    },
    [],
  );

  const identify = useCallback(async (newUser: UserContext): Promise<void> => {
    if (clientRef.current) {
      await clientRef.current.identify(newUser);
    }
  }, []);

  const reset = useCallback(async (): Promise<void> => {
    if (clientRef.current) {
      await clientRef.current.reset();
    }
  }, []);

  const refresh = useCallback(async (): Promise<void> => {
    if (clientRef.current) {
      await clientRef.current.refresh();
    }
  }, []);

  const track = useCallback((options: TrackEventOptions): void => {
    if (clientRef.current) {
      clientRef.current.track(options);
    }
  }, []);

  const getMetrics = useCallback((): MetricsSnapshot => {
    if (clientRef.current) {
      return clientRef.current.getMetrics();
    }
    // Return empty metrics when client not ready
    return {
      totalRequests: 0,
      successfulRequests: 0,
      failedRequests: 0,
      successRate: 0,
      errorRate: 0,
      avgLatencyMs: 0,
      minLatencyMs: 0,
      maxLatencyMs: 0,
      p50LatencyMs: 0,
      p95LatencyMs: 0,
      p99LatencyMs: 0,
      cacheHits: 0,
      cacheMisses: 0,
      cacheHitRate: 0,
      notModifiedResponses: 0,
      errorsByCategory: {},
      circuitOpens: 0,
      circuitCloses: 0,
      circuitState: "closed",
      flagEvaluations: {
        totalEvaluations: 0,
        evaluationsPerFlag: {},
        avgEvaluationTimeMs: 0,
      },
      windows: {
        "1m": { requests: 0, errors: 0, avgLatencyMs: 0, errorRate: 0 },
        "5m": { requests: 0, errors: 0, avgLatencyMs: 0, errorRate: 0 },
        "15m": { requests: 0, errors: 0, avgLatencyMs: 0, errorRate: 0 },
        "1h": { requests: 0, errors: 0, avgLatencyMs: 0, errorRate: 0 },
      },
      uptimeMs: 0,
      lastRequestAt: null,
    };
  }, []);

  const value: RollgateContextValue = {
    isEnabled,
    isLoading,
    isError,
    isStale,
    circuitState,
    flags,
    identify,
    reset,
    refresh,
    getMetrics,
    track,
    client: clientRef.current,
  };

  return React.createElement(RollgateContext.Provider, { value }, children);
}

/**
 * Hook to check if a single flag is enabled
 *
 * @example
 * ```tsx
 * const showNewFeature = useFlag('new-feature', false);
 * ```
 */
export function useFlag(
  flagKey: string,
  defaultValue: boolean = false,
): boolean {
  const context = useContext(RollgateContext);

  if (!context) {
    throw new Error("useFlag must be used within a RollgateProvider");
  }

  return context.isEnabled(flagKey, defaultValue);
}

/**
 * Hook to check if a single flag is enabled with evaluation reason
 *
 * @example
 * ```tsx
 * const { value, reason } = useFlagDetail('new-feature', false);
 * ```
 */
export function useFlagDetail(
  flagKey: string,
  defaultValue: boolean = false,
): EvaluationDetail<boolean> {
  const context = useContext(RollgateContext);

  if (!context) {
    throw new Error("useFlagDetail must be used within a RollgateProvider");
  }

  if (context.client) {
    return context.client.isEnabledDetail(flagKey, defaultValue);
  }

  return {
    value: defaultValue,
    reason: { kind: "ERROR", errorKind: "CLIENT_NOT_READY" },
  };
}

/**
 * Hook to get multiple flags at once
 *
 * @example
 * ```tsx
 * const flags = useFlags(['feature-a', 'feature-b']);
 * ```
 */
export function useFlags(flagKeys: string[]): Record<string, boolean> {
  const context = useContext(RollgateContext);

  if (!context) {
    throw new Error("useFlags must be used within a RollgateProvider");
  }

  const result: Record<string, boolean> = {};
  for (const key of flagKeys) {
    result[key] = context.isEnabled(key, false);
  }
  return result;
}

/**
 * Hook to get a string flag value
 *
 * @example
 * ```tsx
 * const buttonColor = useStringFlag('button-color', 'blue');
 * ```
 */
export function useStringFlag(flagKey: string, defaultValue: string): string {
  const context = useContext(RollgateContext);

  if (!context) {
    throw new Error("useStringFlag must be used within a RollgateProvider");
  }

  if (context.client) {
    return context.client.getString(flagKey, defaultValue);
  }
  return defaultValue;
}

/**
 * Hook to get a number flag value
 *
 * @example
 * ```tsx
 * const maxItems = useNumberFlag('max-items', 10);
 * ```
 */
export function useNumberFlag(flagKey: string, defaultValue: number): number {
  const context = useContext(RollgateContext);

  if (!context) {
    throw new Error("useNumberFlag must be used within a RollgateProvider");
  }

  if (context.client) {
    return context.client.getNumber(flagKey, defaultValue);
  }
  return defaultValue;
}

/**
 * Hook to get a JSON flag value
 *
 * @example
 * ```tsx
 * const config = useJSONFlag('feature-config', { enabled: false });
 * ```
 */
export function useJSONFlag<T>(flagKey: string, defaultValue: T): T {
  const context = useContext(RollgateContext);

  if (!context) {
    throw new Error("useJSONFlag must be used within a RollgateProvider");
  }

  if (context.client) {
    return context.client.getJSON<T>(flagKey, defaultValue);
  }
  return defaultValue;
}

/**
 * Hook to access the full Rollgate context
 *
 * @example
 * ```tsx
 * const { identify, refresh, circuitState } = useRollgate();
 * ```
 */
export function useRollgate(): RollgateContextValue {
  const context = useContext(RollgateContext);

  if (!context) {
    throw new Error("useRollgate must be used within a RollgateProvider");
  }

  return context;
}

/**
 * Hook to access SDK metrics
 *
 * @example
 * ```tsx
 * const { metrics } = useMetrics();
 * console.log(metrics.requests.total);
 * ```
 */
export function useMetrics(): { metrics: MetricsSnapshot } {
  const context = useContext(RollgateContext);

  if (!context) {
    throw new Error("useMetrics must be used within a RollgateProvider");
  }

  return {
    metrics: context.getMetrics(),
  };
}

/**
 * Component that renders children only if flag is enabled
 *
 * @example
 * ```tsx
 * <Feature flag="new-dashboard" fallback={<OldDashboard />}>
 *   <NewDashboard />
 * </Feature>
 * ```
 */
interface FeatureProps {
  flag: string;
  children: ReactNode;
  fallback?: ReactNode;
}

export function Feature({
  flag,
  children,
  fallback = null,
}: FeatureProps): React.ReactElement {
  const enabled = useFlag(flag);
  return React.createElement(
    React.Fragment,
    null,
    enabled ? children : fallback,
  );
}

// Re-export types for backwards compatibility
export type { RollgateContextValue, RollgateProviderProps, FeatureProps };
